import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import "./globals.css";

import Sidebar from "@/components/layout/Sidebar";
import Header from "@/components/layout/Header";

const manrope = Manrope({
  subsets: ["latin", "cyrillic"],
  variable: "--font-manrope",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" className={manrope.variable}>
      <body
        className={`${manrope.className} min-h-screen antialiased font-sans`}
      >
        <div className="flex min-h-screen">
          
          {/* Sidebar */}
          <Sidebar />

          {/* Content */}
          <div className="flex flex-1 flex-col min-w-0">
            
            {/* Header */}
            <div className="container">
              <Header />
            </div>

            {/* Main */}
            <main className="flex-1">
              <div className="container">
                {children}
              </div>
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}